Add starknet support for SAG
Cypher-Laboratory/Alice-s-Ring pull request #13
Opened 2024-09-26 12:52 UTC by LeJamon

Add a new SAG package tailored for starknet (starknet-sag-ts). 
This package is made to suits an on-chain verification in cairo and utilises Garaga MSM hint to do so.

2024-09-27 13:51 UTC, Elli610 reviewed
I guess the `coverage` folder should be added to the `.gitignore`

2024-09-27 13:52 UTC, Elli610 commented
Can you remove all the `.DS_Store` files ?

2024-09-27 13:58 UTC, Elli610 commented
I think we should rename the `starknet-sag-ts` to `cairo-sag-ts` to be more accurate. What do you think ?

2024-09-27 14:06 UTC, Elli610 commented
The tests for `./packages/starknet-sag-ts/src/ringSignature.ts` are missing

2024-09-27 14:14 UTC, Elli610 commented
we also need a read me to understand the purpose of the new package (if we do not merge it with `sag-ts`) and how we can run the code

2024-09-27 14:16 UTC, Elli610 commented
Looks like you forgot to add the commands for this new package in the makefile

2024-09-29 13:25 UTC, LeJamon commented
> I think we should rename the `starknet-sag-ts` to `cairo-sag-ts` to be more accurate. What do you think ?

We should keep the name "starknet-sag-ts" rather than changing to "cairo-sag-ts". The implementation is specific to Starknet, not just Cairo in general. It includes Starknet-specific features like calldata generation. The current name accurately reflects its purpose and target platform.

2024-09-29 13:30 UTC, LeJamon commented
> It looks like the `./packages/starknet-sag-ts/src/ringSignature.ts` file have a lot in common with the ` ./packages/sag-ts/ringSignature.ts`. Why didn't you added a value in the config as we did with the evm signatures ?

While they share common logic, combining them with a config approach (as done with EVM signatures) would result in overly complex code structures with numerous switch cases or nested if statements within functions. This would likely reduce code readability and maintainability.

2024-09-30 09:05 UTC, LeJamon commented
> I guess the `coverage` folder should be added to the `.gitignore`

done

2024-09-30 09:06 UTC, LeJamon commented
> we also need a readme to understand the purpose of the new package (if we do not merge it with `sag-ts`) and how we can run the code

done

2024-09-30 09:06 UTC, LeJamon commented
> Looks like you forgot to add the commands for this new package in the makefile

done

2024-09-30 11:49 UTC, Elli610 commented
Can you remove the package.lock file ? We should only have a yarn.lock

2024-09-30 11:50 UTC, Elli610 commented
some DS_STORE remains (ex: packages/.DS_Store)

2024-09-30 11:52 UTC, Elli610 commented on packages/starknet-sag-ts/src/signature/piSignature.ts
> +*/
```suggestion
```

2024-09-30 11:53 UTC, Elli610 commented on packages/starknet-sag-ts/src/starknet-utils/cairo-utils.ts
> +}
description does not match the method content

2024-09-30 11:55 UTC, Elli610 commented on packages/starknet-sag-ts/src/starknet-utils/garaga-utils.ts
> +// eslint-disable-next-line
```suggestion
/* eslint-disable-next-line @typescript-eslint/no-explicit-any */
```

2024-09-30 11:56 UTC, Elli610 requested changes
ci need to be fixed

2024-09-30 13:01 UTC, LeJamon commented
> Can you remove the package.lock file ? We should only have a yarn.lock

done

2024-09-30 13:01 UTC, LeJamon commented
> some DS_STORE remains (ex: packages/.DS_Store)

done

2024-09-30 13:02 UTC, LeJamon commented
> ci need to be fixed

done

2024-09-30 13:07 UTC, Elli610 commented
> > some DS_STORE remains (ex: packages/.DS_Store)
> 
> done

there are others files like this (ex: packages/starknet-sag-ts/src/signature/.DS_Store)

2024-09-30 13:10 UTC, LeJamon commented
> > > some DS_STORE remains (ex: packages/.DS_Store)
> > 
> > 
> > done
> 
> there are others files like this (ex: packages/starknet-sag-ts/src/signature/.DS_Store)

I have deleted all of them

2024-10-03 08:53 UTC, Elli610 approved these changes
lgtm

2024-10-03 08:53 UTC, merged